Sprint 2/step 2
IvansSmirnoff/burgers pull request #3
Opened 2023-08-20 13:07 UTC by IvansSmirnoff

Я не понимаю, как нормально "инициализировать" всю "конструкторную" часть. Не считая этой (довольно важной!) детали всё работает xD

2023-08-20 14:50 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошо настроен и работает `Dnd` 
- Созданы все необходимые типы экшенов
- Отдельно храните булки и ингредиенты

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:

- Конструктор убежал под список ингредиентов. А должен быть с правой стороны.

<img width="755" alt="Снимок экрана 2023-08-20 в 17 34 49" src="https://github.com/IvansSmirnoff/burgers/assets/60173362/f44849fe-bccc-49ab-80f0-9f23692961cf">

- При добавлении в конструктор булок - у них не меняется счетчик.
- при добавлении ингредиента в конструктор id нужно генерировать и передавать в экшене
- Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

**Можно лучше**
- Не позволяйте юзеру делать заказ пустого конструктора - это вызывает ошибку.
<img width="984" alt="Снимок экрана 2023-08-20 в 17 36 40" src="https://github.com/IvansSmirnoff/burgers/assets/60173362/aa5fe408-80b6-42d5-9ea3-93b0b7be4d2a">

- Конструктор лучше обнулять после оформления заказа, чтобы юзеру не пришлось самому удалять ингредиенты.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-08-20 14:50 UTC, andryxxa93 commented on src/components/burger-constructor/burgerconstructor.jsx
> +	} = useSelector(state => ({
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-08-20 14:50 UTC, andryxxa93 commented on src/services/actions/order.jsx
> +const checkResponse = (res) => {
**Можно лучше**

проверка ответа сервера и преобразование из json дублируется в нескольких местах, нужно вынести в отдельную функцию:

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

2023-08-20 14:50 UTC, andryxxa93 commented on src/services/reducers/constructor-ingredients.jsx
> +			let newItem = addUniqueKeyIds(action.payload);
**Надо исправить**

редьюсер должен быть чистой функции, сейчас при каждом вызове добавления ингредиента результат будет отличаться, даже если стейт и экшен одинаковые - будет генерироваться каждый раз новый id,  при добавлении ингредиента в конструктор id нужно генерировать и передавать в экшене, а не генерировать в редьюсере. Иначе это делает редьюсер не чистой функцией, что нарушает правило редьюсеров

2023-08-20 14:50 UTC, andryxxa93 commented on src/services/reducers/constructor-ingredients.jsx
> +			let newTotalPrice = state.ingredients.reduce((price, currItem) => {
**Можно лучше**

Хотя в задании и предложено вычислять полную стоимость в редьюсере, но это плохая идея, т.к. общая стоимость это производные данные от данных о бургере и сейчас у нас в некотором роде дублируется эта информация (есть массив ингредиентов с ценами и есть отдельно полная стоимость)

Поэтому лучше рассчитывать их не в редьюсере а просто в компоненте конструктора используя useMemo

```
const totalPrice = useMemo(()=> {
   return **рассчет стоимости**
}, burgersData)
```

так стоимость будет перерасчитываться в момент изменения бургера

2023-08-22 16:35 UTC, IvansSmirnoff commented on src/components/burger-constructor/burgerconstructor.jsx
> +	} = useSelector(state => ({
Посмотрел видос и попробовал в паре мест, но не уверен, что эффективно)

2023-08-22 16:43 UTC, IvansSmirnoff commented on src/services/reducers/constructor-ingredients.jsx
> +			let newTotalPrice = state.ingredients.reduce((price, currItem) => {
Так действительно лучше, но, скорее всего, я исправлю это в грядущем спринте, потому что ничего не успеваю

2023-08-22 16:45 UTC, IvansSmirnoff commented on src/services/actions/order.jsx
> +const checkResponse = (res) => {
Нужно в целом устаканить работу с запросами "вовне". Объединю в следующем спринте

2023-08-23 05:45 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-12-05 11:55 UTC, merged